[general]
import = [
  "~/.config/alacritty/themes/night-owl.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "buttonless"
opacity = 0.8
blur = true

option_as_alt = "Both"

[font]
normal.family = "MesloLGS Nerd Font Mono" 



